[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000

# Optional: cache Next build artifacts for faster builds
[[plugins]]
  package = "@netlify/plugin-nextjs"
